2016-10-21 21:54:31,207 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 21:54:31,650 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 22:18:22,878 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 22:26:25,390 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 23:44:51,680 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 23:44:52,119 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 23:49:14,441 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 23:49:14,941 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 23:54:03,388 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 23:54:03,917 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 23:56:15,762 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-21 23:56:16,200 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:03:05,618 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:03:06,089 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:08:44,183 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:08:44,582 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:11:59,098 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:11:59,480 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:13:24,970 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:13:25,450 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:14:04,917 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 00:14:05,440 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 10:41:43,203 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 10:41:44,058 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 11:24:02,546 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 11:24:02,881 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:42:21,673 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:42:40,408 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:43:14,170 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:43:32,802 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:44:15,802 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:44:29,446 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:44:58,183 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:45:28,927 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 12:45:45,579 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:03:03,792 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:03:04,157 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:05:40,269 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:05:40,592 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:33:15,335 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:33:27,144 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:33:43,107 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:33:43,448 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:35:05,742 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:43:51,816 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:43:52,368 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:45:15,861 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:45:30,762 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:46:28,789 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:47:39,030 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:47:44,335 ERROR: Exception on /stocks/cabinets [GET] [in D:\SoftWare\Python27\lib\site-packages\flask\app.py:1587]
Traceback (most recent call last):
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\SoftWare\Python27\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "d:\Scripts\Python\yinfeng\POS\app\views.py", line 163, in postcate
    stocklist = Stock.query.filter_by(categroies=cate1.categroies).all()
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 1514, in filter_by
    for key, value in kwargs.items()]
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Stock'>' has no property 'categroies'
2016-10-22 13:47:48,969 ERROR: Exception on /stocks/chairs [GET] [in D:\SoftWare\Python27\lib\site-packages\flask\app.py:1587]
Traceback (most recent call last):
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\SoftWare\Python27\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "d:\Scripts\Python\yinfeng\POS\app\views.py", line 163, in postcate
    stocklist = Stock.query.filter_by(categroies=cate1.categroies).all()
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 1514, in filter_by
    for key, value in kwargs.items()]
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Stock'>' has no property 'categroies'
2016-10-22 13:47:56,575 ERROR: Exception on /stocks/sofa [GET] [in D:\SoftWare\Python27\lib\site-packages\flask\app.py:1587]
Traceback (most recent call last):
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\SoftWare\Python27\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "d:\Scripts\Python\yinfeng\POS\app\views.py", line 163, in postcate
    stocklist = Stock.query.filter_by(categroies=cate1.categroies).all()
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 1514, in filter_by
    for key, value in kwargs.items()]
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Stock'>' has no property 'categroies'
2016-10-22 13:49:10,259 ERROR: Exception on /stocks/cabinets [GET] [in D:\SoftWare\Python27\lib\site-packages\flask\app.py:1587]
Traceback (most recent call last):
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\SoftWare\Python27\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "d:\Scripts\Python\yinfeng\POS\app\views.py", line 163, in postcate
    stocklist = Stock.query.filter_by(categroies=cate1.categroies).all()
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 1514, in filter_by
    for key, value in kwargs.items()]
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Stock'>' has no property 'categroies'
2016-10-22 13:49:16,351 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:49:18,025 ERROR: Exception on /stocks/cabinets [GET] [in D:\SoftWare\Python27\lib\site-packages\flask\app.py:1587]
Traceback (most recent call last):
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\SoftWare\Python27\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "d:\Scripts\Python\yinfeng\POS\app\views.py", line 163, in postcate
    stocklist = Stock.query.filter_by(categroies=cate1.categroies).all()
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 1514, in filter_by
    for key, value in kwargs.items()]
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Stock'>' has no property 'categroies'
2016-10-22 13:49:55,775 ERROR: Exception on /stocks/cabinets [GET] [in D:\SoftWare\Python27\lib\site-packages\flask\app.py:1587]
Traceback (most recent call last):
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\SoftWare\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\SoftWare\Python27\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "d:\Scripts\Python\yinfeng\POS\app\views.py", line 163, in postcate
    stocklist = Stock.query.filter_by(categroies=cate1.categroies).all()
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 1514, in filter_by
    for key, value in kwargs.items()]
  File "D:\SoftWare\Python27\lib\site-packages\sqlalchemy\orm\base.py", line 383, in _entity_descriptor
    (description, key)
InvalidRequestError: Entity '<class 'app.models.Stock'>' has no property 'categroies'
2016-10-22 13:50:11,609 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
2016-10-22 13:50:11,953 INFO: App started [in d:\Scripts\Python\yinfeng\POS\app\__init__.py:26]
